-- Таблицы «чего и где не хватает» для обращения за помощью. Только чтение базы; файлы CSV пишутся в текущую папку.
\set ON_ERROR_STOP on
set work_mem = '2GB';
create temp table d as select g::date dat from generate_series('1998-01-01'::date, '2022-02-01', interval '1 month') g;
-- банк считается действующим на дату: лицензия начата (или дата начала неизвестна, но банк уже отчитывался) и дата не позже конца
create temp table act as
select f.regn, f.name, d.dat, f.lic_start, f.death_date, f.first_rep, f.last_rep
  from m.fate f join d on d.dat >= coalesce(date_trunc('month', f.lic_start)::date, f.first_rep) and d.dat <= coalesce(date_trunc('month', f.death_date)::date, '2022-02-01');
create temp table have as select regn, dat, (assets > 0) ok from m.bank_date;
\copy (select d.dat as "отчётная дата", (select count(*) from have h where h.dat = d.dat) as "банков в базе", (select count(*) from have h where h.dat = d.dat and h.ok) as "из них с пригодным балансом", (select count(*) from act a where a.dat = d.dat) as "должно быть по справочнику судеб", (select count(*) from act a where a.dat = d.dat and not exists (select 1 from have h where h.regn = a.regn and h.dat = a.dat)) as "нет отчёта", case when not exists (select 1 from have h where h.dat = d.dat) then 'месяц отсутствует целиком' else '' end as "примечание" from d order by 1) to '01_охват_по_датам.csv' csv header
\copy (select a.regn as "рег. номер", a.name as "название", a.dat as "отчётная дата", case when not exists (select 1 from have h where h.dat = a.dat) then 'месяц отсутствует в базе целиком' when a.dat < a.first_rep then 'до первого отчёта банка в базе' when a.dat > a.last_rep then 'после последнего отчёта банка в базе' else 'дыра: банк отчитывался до и после' end as "вид пробела", a.lic_start as "начало лицензии", a.death_date as "конец деятельности", a.first_rep as "первый отчёт в базе", a.last_rep as "последний отчёт в базе" from act a where not exists (select 1 from have h where h.regn = a.regn and h.dat = a.dat) order by a.dat, a.regn) to '02_нет_отчёта_банк_дата.csv' csv header
\copy (select g.kind as "вид недостатка", g.regn as "рег. номер", f.name as "название", g.dat as "отчётная дата", g.detail as "пояснение" from m.dig_gap g left join m.fate f using (regn) where g.kind in ('нет валюты баланса','остатки восстановлены, оборотов нет','нет деления остатков на рубли и валюту','нет деления остатков на рубли и валюту: в обоих источниках валюта записана в рублёвый столбец','сумма долей листьев не равна единице','баланс не сходится','скачок валюты баланса') order by 1, 4, 2) to '03_пробелы_содержания.csv' csv header
\copy (select kind as "вид недостатка", count(*) as "случаев", count(distinct regn) as "банков", min(dat) as "с", max(dat) as "по" from m.dig_gap group by 1 order by 2 desc) to '03_сводка_видов.csv' csv header
\copy (select f.regn as "рег. номер", f.name as "название", f.first_rep as "первый отчёт в базе", f.last_rep as "последний отчёт в базе", f.lic_start as "начало лицензии", f.lic_end as "окончание лицензии", f.revoke_date as "дата отзыва", f.revoke_order as "приказ об отзыве", f.fate as "итог", f.death_kind as "вид конца", f.successor_regn as "правопреемник", f.evidence as "на чём основана запись", concat_ws('; ', case when f.death_kind = 'revoked_reason_unknown' then 'причина отзыва: номер и дата приказа, основания (текст приказа или выпуск «Вестника Банка России»)' end, case when f.death_kind = 'ended_kind_unknown' then 'вид прекращения: отзыв, аннулирование, присоединение или иное; дата и документ' end, case when f.fate = 'merged' and f.successor_regn is null then 'правопреемник: рег. номер банка, к которому присоединён' end, case when f.lic_start is null then 'дата регистрации (начала лицензии)' end, case when f.fate in ('stopped_reporting_but_active', 'liquidated_reason_unknown') then 'что произошло с банком после последнего отчёта' end, case when f.revoke_date is not null and f.revoke_order is null then 'номер приказа об отзыве' end) as "что нужно" from m.fate f where f.death_kind in ('revoked_reason_unknown', 'ended_kind_unknown') or (f.fate = 'merged' and f.successor_regn is null) or f.lic_start is null or f.fate in ('stopped_reporting_but_active', 'liquidated_reason_unknown') or (f.revoke_date is not null and f.revoke_order is null) order by f.regn) to '04_судьбы_розыск.csv' csv header
\copy (select f.regn as "рег. номер", f.name as "название", f.revoke_date as "дата отзыва", f.revoke_order as "приказ", f.death_kind as "наша разметка причины", f.death_kind_src as "источник разметки", f.reason_detail as "уточнение" from m.fate f where f.fate = 'licence_revoked' and f.death_kind in ('economic', 'aml', 'other', 'false_only') order by f.revoke_date) to '05_причины_отзыва_на_проверку.csv' csv header
